# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('name_for_bib_number', models.CharField(max_length=200, verbose_name='nome para número de peito')),
                ('gender', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1, verbose_name='sexo')),
                ('date_of_birth', models.DateField(verbose_name='data de nascimento')),
                ('city', models.CharField(max_length=100, verbose_name='cidade')),
                ('team', models.CharField(max_length=100, verbose_name='equipe')),
                ('shirt_size', models.CharField(max_length=25, verbose_name='tamanho da camiseta')),
                ('modality', models.CharField(max_length=25, verbose_name='modalidade')),
            ],
        ),
    ]
