# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name_for_bib_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='nome para número de peito'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='team',
            field=models.CharField(blank=True, max_length=100, verbose_name='equipe'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='import_t',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Import'),
        ),
    ]
