# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import subscriptions.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_import_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('column_name', models.CharField(choices=[('name', 'name'), ('email', 'email'), ('name_for_bib_number', 'name_for_bib_number'), ('gender', 'gender'), ('date_of_birth', 'date_of_birth'), ('city', 'city'), ('team', 'team'), ('shirt_size', 'shirt_size'), ('modality', 'modality')], default='', max_length=20, verbose_name='coluna')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='import',
            name='file',
            field=models.FileField(upload_to='', validators=[subscriptions.core.validators.ValidateFile.columns]),
        ),
    ]
