# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170525_0450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='id',
            new_name='file_name',
        ),
        migrations.RemoveField(
            model_name='column',
            name='column_name',
        ),
        migrations.AddField(
            model_name='column',
            name='subscription_name',
            field=models.CharField(choices=[('name', 'name'), ('email', 'email'), ('name_for_bib_number', 'name_for_bib_number'), ('gender', 'gender'), ('date_of_birth', 'date_of_birth'), ('city', 'city'), ('team', 'team'), ('shirt_size', 'shirt_size'), ('modality', 'modality'), ('ignore', 'ignore')], default='', max_length=20, verbose_name='coluna'),
        ),
    ]
