# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_shirtsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='shirt_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ShirtSize'),
        ),
    ]
