# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170530_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirtsize',
            name='shirt_size',
            field=models.CharField(choices=[('BL', 'Baby Look'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('2', 'Infantil 2'), ('4', 'Infantil 4'), ('6', 'Infantil 6'), ('8', 'Infantil 8'), ('10', 'Infantil 10'), ('12', 'Infantil 12'), ('14', 'Infantil 14')], default='', max_length=10, verbose_name='camiseta'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='shirt_size',
            field=models.CharField(choices=[('BL', 'Baby Look'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('2', 'Infantil 2'), ('4', 'Infantil 4'), ('6', 'Infantil 6'), ('8', 'Infantil 8'), ('10', 'Infantil 10'), ('12', 'Infantil 12'), ('14', 'Infantil 14')], max_length=20, verbose_name='tamanho da camiseta'),
        ),
    ]
