# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170530_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='subscription_name',
            field=models.CharField(choices=[('name', 'name'), ('email', 'email'), ('name_for_bib_number', 'name_for_bib_number'), ('gender', 'gender'), ('date_of_birth', 'date_of_birth'), ('city', 'city'), ('team', 'team'), ('shirt_size', 'shirt_size'), ('modality', 'modality'), ('ignore', 'ignore')], max_length=20, verbose_name='coluna'),
        ),
        migrations.AlterField(
            model_name='shirtsize',
            name='shirt_size',
            field=models.CharField(choices=[('BL', 'Baby Look'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('2', 'Infantil 2'), ('4', 'Infantil 4'), ('6', 'Infantil 6'), ('8', 'Infantil 8'), ('10', 'Infantil 10'), ('12', 'Infantil 12'), ('14', 'Infantil 14')], max_length=10, verbose_name='camiseta'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='import_t',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Import'),
        ),
    ]
