# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170612_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='date_format',
            field=models.CharField(blank=True, default='%d/%m/%Y', max_length=15, null=True, verbose_name='formato da data'),
        ),
    ]
