# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_import_date_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(choices=[('1', '1km'), ('2', '2km'), ('3', '3km'), ('4', '4km'), ('5', '5km'), ('6', '6km'), ('7', '7km'), ('8', '8km'), ('9', '9km'), ('10', '10km'), ('I', 'Infantil'), ('J', 'Juvenil'), ('C', 'Caminhada')], max_length=1, verbose_name='modalidade')),
                ('file_modality', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='modality',
            field=models.CharField(choices=[('1', '1km'), ('2', '2km'), ('3', '3km'), ('4', '4km'), ('5', '5km'), ('6', '6km'), ('7', '7km'), ('8', '8km'), ('9', '9km'), ('10', '10km'), ('I', 'Infantil'), ('J', 'Juvenil'), ('C', 'Caminhada')], max_length=1, verbose_name='modalidade'),
        ),
    ]
