# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170622_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='file_name',
            new_name='file_column',
        ),
    ]
