# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170624_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='paid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='pago'),
        ),
        migrations.AlterField(
            model_name='column',
            name='subscription_name',
            field=models.CharField(choices=[('name', 'name'), ('email', 'email'), ('name_for_bib_number', 'name_for_bib_number'), ('gender', 'gender'), ('date_of_birth', 'date_of_birth'), ('city', 'city'), ('team', 'team'), ('shirt_size', 'shirt_size'), ('modality', 'modality'), ('ignore', 'ignore'), ('paid', 'paid')], max_length=20, verbose_name='coluna'),
        ),
        migrations.AlterField(
            model_name='modality',
            name='modality',
            field=models.CharField(choices=[('1', '1km'), ('2', '2km'), ('3', '3km'), ('4', '4km'), ('5', '5km'), ('6', '6km'), ('7', '7km'), ('8', '8km'), ('9', '9km'), ('10', '10km'), ('C', 'Caminhada'), ('I', 'Infantil'), ('J', 'Juvenil'), ('K', 'Kangoo'), ('Q', 'Quarteto')], max_length=2, verbose_name='modalidade'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='modality',
            field=models.CharField(choices=[('1', '1km'), ('2', '2km'), ('3', '3km'), ('4', '4km'), ('5', '5km'), ('6', '6km'), ('7', '7km'), ('8', '8km'), ('9', '9km'), ('10', '10km'), ('C', 'Caminhada'), ('I', 'Infantil'), ('J', 'Juvenil'), ('K', 'Kangoo'), ('Q', 'Quarteto')], max_length=2, verbose_name='modalidade'),
        ),
    ]
